/**
 * ========================================
 * ALPHA CHECK SERVICE
 * ========================================
 * Service untuk mengecek karyawan yang tidak absen
 * dan mencatat status ALPHA secara otomatis
 *
 * Potongan: Rp 100.000 per hari alpha
 *
 * @author HRIS Development Team
 * @version 2.0.0
 */

const cron = require("node-cron");

class AlphaCheckService {
  constructor(prisma) {
    this.prisma = prisma;
    console.log("🤖 AlphaCheckService initialized");
  }

  /**
   * Check alpha untuk tanggal tertentu
   * @param {Date} checkDate - Tanggal yang akan dicek
   * @returns {Object} Result dengan detail alpha yang ditemukan
   */
  async checkAlphaForDate(checkDate) {
    console.log("\n" + "=".repeat(60));
    console.log("🔍 ALPHA CHECK SERVICE");
    console.log("=".repeat(60));
    console.log("📅 Checking date:", checkDate.toISOString().split("T")[0]);

    try {
      // 1. Get all active employees (tidak resign)
      const activeEmployees = await this.prisma.employee.findMany({
        where: {
          status_karyawan: {
            not: "Resign",
          },
        },
        include: {
          user: {
            select: {
              status_karyawan: true,
            },
          },
        },
      });

      console.log(`👥 Active employees: ${activeEmployees.length}`);

      // 2. Get all attendance records untuk tanggal yang dicek
      const startOfDay = new Date(checkDate);
      startOfDay.setHours(0, 0, 0, 0);

      const endOfDay = new Date(checkDate);
      endOfDay.setHours(23, 59, 59, 999);

      const attendanceRecords = await this.prisma.attendance.findMany({
        where: {
          tanggal: {
            gte: startOfDay,
            lte: endOfDay,
          },
        },
      });

      console.log(`📋 Attendance records found: ${attendanceRecords.length}`);

      // 3. Find employees without attendance
      const attendedEmployeeIds = new Set(
        attendanceRecords.map((a) => a.employee_id)
      );

      const absentEmployees = activeEmployees.filter(
        (emp) => !attendedEmployeeIds.has(emp.employee_id)
      );

      console.log(`❌ Employees without attendance: ${absentEmployees.length}`);

      // 4. Check for approved leaves
      const approvedLeaves = await this.prisma.leaveRequest.findMany({
        where: {
          status: "approved",
          tanggal_mulai: {
            lte: endOfDay,
          },
          tanggal_selesai: {
            gte: startOfDay,
          },
        },
      });

      const employeesOnLeave = new Set(
        approvedLeaves.map((leave) => leave.employee_id)
      );

      console.log(`🏖️ Employees on approved leave: ${employeesOnLeave.size}`);

      // 5. Create ALPHA records untuk employees tanpa attendance dan tidak cuti
      const alphaRecords = [];

      for (const employee of absentEmployees) {
        // Skip jika employee sedang cuti approved
        if (employeesOnLeave.has(employee.employee_id)) {
          console.log(
            `  ✓ Skipping employee ${employee.employee_id} (${employee.nama_lengkap}) - On approved leave`
          );
          continue;
        }

        try {
          // Create alpha record
          const alphaRecord = await this.prisma.attendance.create({
            data: {
              employee_id: employee.employee_id,
              tanggal: checkDate,
              jam_masuk: null,
              jam_pulang: null,
              status: "alpa",
              keterangan:
                "Alpha - Tidak ada absensi tercatat hingga 23:00 (Auto-generated by system)",
              tipe_kerja: "WFO",
              lokasi_masuk: null,
              lokasi_pulang: null,
              recorded_by_role: "System",
              approval_status: "approved",
            },
          });

          alphaRecords.push({
            employee_id: employee.employee_id,
            nama_lengkap: employee.nama_lengkap,
            attendance_id: alphaRecord.attendance_id,
          });

          console.log(
            `  ❌ ALPHA recorded for: ${employee.nama_lengkap} (ID: ${employee.employee_id})`
          );
        } catch (error) {
          console.error(
            `  ⚠️ Error creating alpha for employee ${employee.employee_id}:`,
            error.message
          );
        }
      }

      console.log("\n" + "=".repeat(60));
      console.log("✅ ALPHA CHECK COMPLETED");
      console.log(`   Total alpha recorded: ${alphaRecords.length}`);
      console.log("=".repeat(60) + "\n");

      return {
        success: true,
        date: checkDate.toISOString().split("T")[0],
        total_employees: activeEmployees.length,
        total_attended: attendanceRecords.length,
        total_on_leave: employeesOnLeave.size,
        total_alpha: alphaRecords.length,
        alpha_records: alphaRecords,
      };
    } catch (error) {
      console.error("❌ Error in alpha check:", error);
      return {
        success: false,
        error: error.message,
      };
    }
  }

  /**
   * Check alpha untuk kemarin
   * @returns {Object} Result dari alpha check
   */
  async checkYesterdayAlpha() {
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    yesterday.setHours(0, 0, 0, 0);

    console.log(
      "📅 Checking yesterday's alpha:",
      yesterday.toISOString().split("T")[0]
    );

    return await this.checkAlphaForDate(yesterday);
  }

  //Check alpha untuk hari ini@returns {Object} Result dari alpha check

  async checkTodayAlpha() {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    console.log(
      "📅 Checking today's alpha:",
      today.toISOString().split("T")[0]
    );

    return await this.checkAlphaForDate(today);
  }

  /**
   * Setup cron job untuk check alpha setiap hari
   * Berjalan setiap hari jam 00:30 WIB (30 menit setelah tengah malam)
   */
  setupCronJob() {
    console.log("⏰ Setting up Alpha Check Cron Job...");
    console.log("   Schedule: Every day at 23:01 WIB"); // ← UBAH INI

    // Cron pattern: "0 18 * * *"
    cron.schedule(
      "1 23 * * *", // ← UBAH INI (jam 23:00)
      async () => {
        console.log(
          "\n🤖 [CRON] Alpha check triggered at:",
          new Date().toISOString()
        );

        try {
          await this.checkTodayAlpha();
        } catch (error) {
          console.error("❌ [CRON] Error during alpha check:", error);
        }
      },
      {
        scheduled: true,
        timezone: "Asia/Jakarta",
      }
    );

    console.log("✅ Cron job setup completed");
    console.log("   Next run: Tomorrow at 23:00 WIB"); // ← UBAH INI
    console.log(
      "   Action: Check employees without attendance and mark as ALPHA"
    );
  }

  /**
   * Manual trigger untuk testing
   * @param {number} daysAgo - Berapa hari yang lalu (default: 1 = kemarin)
   * @returns {Object} Result dari alpha check
   */
  async manualCheckAlpha(daysAgo = 1) {
    const checkDate = new Date();
    checkDate.setDate(checkDate.getDate() - daysAgo);
    checkDate.setHours(0, 0, 0, 0);

    console.log(
      `\n🔧 Manual alpha check triggered for: ${
        checkDate.toISOString().split("T")[0]
      }`
    );
    console.log(`   (${daysAgo} day(s) ago)`);

    return await this.checkAlphaForDate(checkDate);
  }

  /**
   * Get alpha statistics untuk periode tertentu
   * @param {Date|string} startDate - Tanggal mulai
   * @param {Date|string} endDate - Tanggal akhir
   * @returns {Object} Statistik alpha
   */
  async getAlphaStats(startDate, endDate) {
    try {
      // Convert ke Date object jika masih string
      const start =
        typeof startDate === "string" ? new Date(startDate) : startDate;
      const end = typeof endDate === "string" ? new Date(endDate) : endDate;

      console.log("📊 Fetching alpha statistics...");
      console.log(
        `   Period: ${start.toISOString().split("T")[0]} to ${
          end.toISOString().split("T")[0]
        }`
      );

      // Get all alpha records dalam periode
      const alphaRecords = await this.prisma.attendance.findMany({
        where: {
          status: "alpa",
          tanggal: {
            gte: start,
            lte: end,
          },
        },
        include: {
          employee: {
            select: {
              employee_id: true,
              nama_lengkap: true,
              jabatan: true,
            },
          },
        },
        orderBy: {
          tanggal: "desc",
        },
      });

      console.log(`   Found ${alphaRecords.length} alpha records`);

      // Group by employee
      const employeeStats = {};

      alphaRecords.forEach((record) => {
        const empId = record.employee_id;

        if (!employeeStats[empId]) {
          employeeStats[empId] = {
            employee_id: empId,
            nama_lengkap: record.employee.nama_lengkap,
            jabatan: record.employee.jabatan,
            alpha_count: 0,
            total_deduction: 0,
            dates: [],
          };
        }

        employeeStats[empId].alpha_count++;
        employeeStats[empId].total_deduction += 100000; // Rp 100.000 per alpha
        employeeStats[empId].dates.push(
          record.tanggal.toISOString().split("T")[0]
        );
      });

      const result = {
        period: {
          start: start.toISOString().split("T")[0],
          end: end.toISOString().split("T")[0],
        },
        total_alpha_records: alphaRecords.length,
        total_deduction: alphaRecords.length * 100000,
        by_employee: Object.values(employeeStats),
        raw_records: alphaRecords,
      };

      console.log("✅ Statistics generated successfully");

      return result;
    } catch (error) {
      console.error("❌ Error fetching alpha stats:", error);
      throw error;
    }
  }

  /**
   * Get alpha count untuk employee tertentu dalam periode
   * @param {number} employeeId - ID karyawan
   * @param {Date|string} startDate - Tanggal mulai
   * @param {Date|string} endDate - Tanggal akhir
   * @returns {number} Jumlah alpha
   */
  async getEmployeeAlphaCount(employeeId, startDate, endDate) {
    try {
      const start =
        typeof startDate === "string" ? new Date(startDate) : startDate;
      const end = typeof endDate === "string" ? new Date(endDate) : endDate;

      const count = await this.prisma.attendance.count({
        where: {
          employee_id: employeeId,
          status: "alpa",
          tanggal: {
            gte: start,
            lte: end,
          },
        },
      });

      return count;
    } catch (error) {
      console.error("❌ Error getting employee alpha count:", error);
      throw error;
    }
  }

  /**
   * Delete alpha record (untuk rollback/koreksi)
   * @param {number} attendanceId - ID record attendance
   * @returns {boolean} Success status
   */
  async deleteAlphaRecord(attendanceId) {
    try {
      const record = await this.prisma.attendance.findUnique({
        where: { attendance_id: attendanceId },
      });

      if (!record) {
        throw new Error("Alpha record not found");
      }

      if (record.status !== "alpa") {
        throw new Error("This is not an alpha record");
      }

      await this.prisma.attendance.delete({
        where: { attendance_id: attendanceId },
      });

      console.log(`✅ Alpha record deleted: ID ${attendanceId}`);
      return true;
    } catch (error) {
      console.error("❌ Error deleting alpha record:", error);
      throw error;
    }
  }

  /**
   * Convert alpha ke status lain
   * @param {number} attendanceId - ID record attendance
   * @param {string} newStatus - Status baru (hadir, izin, sakit)
   * @param {string} keterangan - Keterangan tambahan
   * @returns {Object} Updated record
   */
  async convertAlphaStatus(attendanceId, newStatus, keterangan = "") {
    try {
      const record = await this.prisma.attendance.findUnique({
        where: { attendance_id: attendanceId },
      });

      if (!record) {
        throw new Error("Alpha record not found");
      }

      if (record.status !== "alpa") {
        throw new Error("This is not an alpha record");
      }

      const validStatuses = ["hadir", "izin", "sakit"];
      if (!validStatuses.includes(newStatus)) {
        throw new Error("Invalid status. Must be: hadir, izin, or sakit");
      }

      const updated = await this.prisma.attendance.update({
        where: { attendance_id: attendanceId },
        data: {
          status: newStatus,
          keterangan: keterangan || `Converted from alpha to ${newStatus}`,
        },
      });

      console.log(`✅ Alpha converted to ${newStatus}: ID ${attendanceId}`);
      return updated;
    } catch (error) {
      console.error("❌ Error converting alpha:", error);
      throw error;
    }
  }
}

// Export class
module.exports = AlphaCheckService;
